Cleanup unused code, as noted by clang
Also update the Makefile to make clang accept the input (i.e. avoid passing header files to the compiler).

Commits:
* dbus: Remove unused variabes
This issue is seen when using clang to compile it
Same fix is needed for parse.c and networkd.c,
Fixes
src/dbus.c:49:23: error: unused variable 'stdout' [-Werror,-Wunused-variable]
g_autofree gchar *stdout = NULL;
^
Signed-off-by: Khem Raj <raj.khem@gmail.com>

* Makefile: Exclude .h files from target rule
This ensures that src/_features.h is not added to compiler cmdline which
can confuse the compilers e.g. clang as it may not like .h as valid input
and complain
| clang-11: error: cannot specify -o when generating multiple output files
| make: *** [Makefile:50: netplan-dbus] Error 1
| make: *** Waiting for unfinished jobs....
Signed-off-by: Khem Raj <raj.khem@gmail.com>