dbus: Remove unused variabes
This issue is seen when using clang to compile it

Same fix is needed for parse.c and networkd.c,

Fixes
src/dbus.c:49:23: error: unused variable 'stdout' [-Werror,-Wunused-variable]
g_autofree gchar *stdout = NULL;
^

Signed-off-by: Khem Raj <raj.khem@gmail.com>