Revert "meson: use absolute link target for generator symlink"
This reverts commit 2ecbc0576590d0cafdf4ba013ff2272873aa07c5.

Meson isn't willing to install a dangling symlink, so we need a better solution
than using an absolute path for this:
```
ERROR: Tried to install symlink to missing file /usr/libexec/netplan/generate
FAILED: meson-install
```