ctests: fix an integer conversion issue
The return type of netplan_netdef_get_output_filename() is signed
size_t. The test was failing on armhf due to a cast issue:

[  ERROR   ] --- 0xfffffffe != 0xfffffffffffffffe
[   LINE   ] --- ../tests/ctests/test_netplan_misc.c:164: error: Failure!