parse: Add the filepath to OVS ports netdefs (#295)
The filepath isn't being populated for OVS ports netdefs.

Add a unit test to catch this issue.

New unit test outcome without the fix:

======================================================================                                                                 
FAIL: test_filepath_for_ovs_ports (test_libnetplan.TestNetDefinition)                                                                                                    
----------------------------------------------------------------------                                                                 
Traceback (most recent call last):
  File "/workspace/netplan-filepath/tests/test_libnetplan.py", line 382, in test_filepath_for_ovs_ports
    self.assertEqual(os.path.join(self.confdir, "a.yaml"), netdef.filepath)
    AssertionError: '/tmp/tmpp3mx4zw6/etc/netplan/a.yaml' != None


COMMITS:
* parse: Add the filepath to OVS ports netdefs

The filepath isn't being populated for OVS ports netdefs.

Add a unit test to catch this issue.

* parse: set filepath correctly after redefinition

When the object is redefined by a different yaml file, the filepath must
be updated to refer to that file.

Add a unit test to check for this invariant.

* parse: rebase & resolve conflicts